"""initial schema

Revision ID: ddd259908cce
Revises:
Create Date: 2026-07-17 10:23:54.998823

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ddd259908cce"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backup_configs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("cron_expression", sa.String(length=100), nullable=False),
        sa.Column("backup_file_prefix", sa.String(length=200), nullable=False),
        sa.Column("method", sa.String(length=30), nullable=False),
        sa.Column("local_path", sa.String(length=500), nullable=True),
        sa.Column("endpoint_url", sa.String(length=500), nullable=True),
        sa.Column("access_key", sa.String(length=200), nullable=True),
        sa.Column("secret_key", sa.String(length=500), nullable=True),
        sa.Column("bucket", sa.String(length=200), nullable=True),
        sa.Column("object_prefix", sa.String(length=300), nullable=True),
        sa.Column("next_run_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "backup_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("method", sa.String(length=30), nullable=False),
        sa.Column("target", sa.String(length=800), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("operator", sa.String(length=100), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "change_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("entity_name", sa.String(length=255), nullable=True),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=True),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("operator", sa.String(length=100), nullable=False),
        sa.Column("operation_method", sa.String(length=30), server_default="client", nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("change_logs", schema=None) as batch_op:
        batch_op.create_index("idx_changelog_created", ["created_at"], unique=False)
        batch_op.create_index("idx_changelog_entity", ["entity_type", "entity_id"], unique=False)

    op.create_table(
        "network_plane_types",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column("vrf", sa.String(length=100), nullable=True),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["network_plane_types.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("network_plane_types", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_network_plane_types_name"), ["name"], unique=True)

    op.create_table(
        "regions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("regions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_regions_name"), ["name"], unique=True)

    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_role"), ["role"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "external_access_tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("scopes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("external_access_tokens", schema=None) as batch_op:
        batch_op.create_index("idx_external_access_token_expires", ["expires_at"], unique=False)
        batch_op.create_index("idx_external_access_token_user", ["user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_external_access_tokens_token_hash"), ["token_hash"], unique=True)

    op.create_table(
        "region_network_planes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("region_id", sa.String(length=36), nullable=False),
        sa.Column("plane_type_id", sa.String(length=36), nullable=False),
        sa.Column("scope", sa.String(length=100), nullable=False),
        sa.Column("cidr", sa.String(length=43), nullable=False),
        sa.Column("vlan_id", sa.Integer(), nullable=True),
        sa.Column("gateway_position", sa.String(length=255), nullable=True),
        sa.Column("gateway_ip", sa.String(length=39), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["plane_type_id"], ["network_plane_types.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["region_id"], ["regions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("region_id", "plane_type_id", "scope", name="uq_region_plane_type_scope"),
    )
    with op.batch_alter_table("region_network_planes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_region_network_planes_vlan_id"), ["vlan_id"], unique=False)

    op.create_table(
        "user_region_permissions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("region_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["region_id"], ["regions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "region_id", name="uq_user_region_permission"),
    )
    with op.batch_alter_table("user_region_permissions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_region_permissions_region_id"), ["region_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_region_permissions_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_region_permissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_region_permissions_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_region_permissions_region_id"))

    op.drop_table("user_region_permissions")
    with op.batch_alter_table("region_network_planes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_region_network_planes_vlan_id"))

    op.drop_table("region_network_planes")
    with op.batch_alter_table("external_access_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_external_access_tokens_token_hash"))
        batch_op.drop_index("idx_external_access_token_user")
        batch_op.drop_index("idx_external_access_token_expires")

    op.drop_table("external_access_tokens")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_role"))

    op.drop_table("users")
    with op.batch_alter_table("regions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_regions_name"))

    op.drop_table("regions")
    with op.batch_alter_table("network_plane_types", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_network_plane_types_name"))

    op.drop_table("network_plane_types")
    with op.batch_alter_table("change_logs", schema=None) as batch_op:
        batch_op.drop_index("idx_changelog_entity")
        batch_op.drop_index("idx_changelog_created")

    op.drop_table("change_logs")
    op.drop_table("backup_records")
    op.drop_table("backup_configs")
    # ### end Alembic commands ###
